# Generated by Django 5.0.1 on 2024-12-21 06:43

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blood_test_api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TestResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('patient_id', models.IntegerField(validators=[django.core.validators.MinValueValidator(1)])),
                ('test_name', models.CharField(choices=[('GLUCOSE', 'Blood Glucose'), ('HB', 'Hemoglobin'), ('CHOL', 'Cholesterol')], max_length=100)),
                ('value', models.DecimalField(decimal_places=2, max_digits=8)),
                ('unit', models.CharField(max_length=10)),
                ('test_date', models.DateTimeField()),
                ('is_abnormal', models.BooleanField()),
            ],
        ),
        migrations.DeleteModel(
            name='BloodTest',
        ),
        migrations.AddIndex(
            model_name='testresult',
            index=models.Index(fields=['patient_id', 'test_name'], name='blood_test__patient_57b7d2_idx'),
        ),
    ]
